export default {
  countdownLabel: 'Countdown',
  iconCountdownLabel: 'fitness',
  restLabel: 'Rest',
  iconRestLabel: 'rest',
  cycleLabel: 'Cycle',
  iconCycleLabel: 'cycle',
  cyclesLabel: 'Cycles',
  serieLabel: 'Serie',
  iconSerieLabel: 'spinner',
  seriesLabel: 'Series',
  stopLabel: 'stop',
  iconRestBetweenLabel: 'timer',
  restBetweenCyclesLabel: 'Rest between cycles',
  completeWorkoutTime: 'Complete workout time: ',
  startCoundownLabel: 'Start countdown',
  iconStartCoundownLabel: 'stopwatch',
  infoSpaceText: `Here you can choose how many seconds each part of the exercise takes. \n\r Countdown is the active time of the workout (60 seconds tops).\n\r Rest is the time you take between workouts (60 seconds tops). \n\r Series and cycles is self explanatory (I hope), if not this app is not for you :D`,
  completedSessionInLabel: 'You have completed a session in ',
  timeLabel: 'time.',
  enterTheDataLabel: 'Enter the data you want for your workout:',
};
